timezone: Europe/Rome
baseurl: "/graf"
permalink: pretty
repository: riminino/graf

# COLLECTIONS
collections:
  docs:
    output: true
    title: Docs

# DEFAULTS
defaults:
  - scope:
      type: docs
    values:
      layout: default
      weight: 1
      classes: [right-sidebar no-header sticky-nav sticky-sidebar]
      sidebar: [toc]

# kramdown syntax is normally not processed inside an HTML tag
# https://kramdown.gettalong.org/quickref.html#html-elements
# inline use {::options parse_block_html="true" /}
# kramdown:
#   parse_block_html: true

css:
  theme: contrast
  # syntax:
  #   dark: rouge/molokai
  #   light: rouge/magritte
