name: Request Page Build
on:
  schedule:
    - cron:  '0 */1 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.requestPagesBuild({
              owner: context.repo.owner,
              repo: context.repo.repo
            })