# Don't use hyphens on the filename
name: Request Page Build
on:
  schedule:
    # At minute 1 past every hour
    #- cron:  '1 */1 * * *'
    - cron: '*/15 * * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get GitHub Pages branch
            const pages = github.repos.getPages({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            // Get branch sha
            //const sha = await github.repos.getBranch({
            //  owner: context.repo.owner,
            //  repo: context.repo.repo,
            //  branch: pages_branch
            //});
             
            github.repos.requestPagesBuild({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            
            // Output
            console.log(pages, pages.source.branch)