# Don't use hyphens on the filename
name: Request Page Build
on:
  schedule:
    # At minute 1 past every hour
    #- cron:  '1 */1 * * *'
    # At minute 1 past every 24th hour
    -cron: '1 */24 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ACTIONS }}
          script: |
            const build = await github.repos.requestPagesBuild({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            console.log(build)
            console.log(context)