# Don't use hyphens on the filename
name: Request Page Build
on:
  schedule:
    # At minute 1 past every hour
    - cron:  '1 */1 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get branch sha
            const sha = octokit.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: main
            });
             
            github.repos.requestPagesBuild({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            console.log(sha)